spring:
  application:
    name: quantum-web-user
  #profiles默认为dev
  profiles:
    active: dev
  cloud:
    nacos:
      server-addr: 47.96.82.135:8848
      username: nacos
      password: mynacos2025
      namespace: Quantum
      discovery:
        namespace: ${spring.cloud.nacos.namespace}
        group: ${spring.profiles.active}
      config:
        namespace: ${spring.cloud.nacos.namespace}
        group: ${spring.profiles.active}

  config:
    import:
      - optional:nacos:${spring.application.name}.yaml?group=${spring.profiles.active}&refreshEnabled=true
      - optional:nacos:quantum-redis.yaml?group=${spring.profiles.active}&refreshEnabled=true
